//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPedidoFornecedor
    {
        public int idPedidoFornecedor { get; set; }
        public int idProduto { get; set; }
        public int idFornecedor { get; set; }
        public string usuario { get; set; }
        public string dataSolicitacao { get; set; }
        public string dataRecebiemnto { get; set; }
        public string stausPedido { get; set; }
        public string quantidiade { get; set; }
    }
}
