//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduto
    {
        public int idProduto { get; set; }
        public int idFornecedor { get; set; }
        public string codigo { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> precoCusto { get; set; }
        public Nullable<decimal> precoVenda { get; set; }
        public string estoqueMinimo { get; set; }
        public string estoque { get; set; }
        public string tipo { get; set; }
    }
}
